=== BauhausLuftfahrt/MATSim-UAM/src/main/resources/dtd/uam.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT uam (stations,vehicleTypes,vehicles)>
<!ELEMENT stations (station)*>
<!ELEMENT vehicleTypes (vehicleType)*>
<!ELEMENT vehicles (vehicle)*>

<!ELEMENT station EMPTY>
<!ATTLIST station	id				CDATA	#REQUIRED
					link  			CDATA	#REQUIRED
					x				CDATA	#IMPLIED
					y				CDATA	#IMPLIED
					name 			CDATA	#IMPLIED
					preflighttime	CDATA	#REQUIRED
					postflighttime	CDATA	#REQUIRED
					defaultwaittime	CDATA	#REQUIRED>
					
<!ELEMENT vehicleType EMPTY>
<!ATTLIST vehicleType	id				CDATA	#REQUIRED
						range			CDATA	#REQUIRED
						capacity		CDATA	#REQUIRED
						cruisespeed		CDATA	#REQUIRED
						verticalspeed	CDATA	#REQUIRED
						turnaroundtime	CDATA	#REQUIRED
						boardingtime	CDATA	#REQUIRED
						deboardingtime	CDATA	#REQUIRED>

<!ELEMENT vehicle EMPTY>
<!ATTLIST vehicle	id				CDATA	#REQUIRED
					type			CDATA	#REQUIRED
					initialstation	CDATA	#REQUIRED
					starttime		CDATA	#IMPLIED
					endtime			CDATA	#IMPLIED>

<!-- ============================================================ -->

<!-- ROOT ELEMENT uam:
     Hold all the information on the Urban Air Mobility stations and
     vehicles -->
     
<!-- ============================================================ -->

<!-- ELEMENT stations:
     Holds all the Urban Air Mobility stations. -->
     
<!-- ELEMENT vehicleTypes:
     Holds all the Urban Air Mobility vehicle types. -->
     
<!-- ELEMENT vehicles:
     Holds all the Urban Air Mobility vehicles. -->

<!-- ============================================================ -->

<!-- ELEMENT station:
     An Urban Air Mobility station. -->
     
<!-- ATTRIBUTE name:
     Each station can be (optionally) provided with a name for easier
     identification.
     format := string -->

<!-- ATTRIBUTE id:
     Each station has to have a unique id.
     format := string -->
     
<!-- ATTRIBUTE preflighttime:
     Each station has to provide the Time needed by the passenger
     to get from the vertiport and entry to his/her aircraft in 
     seconds.
     status := unimplemented
     format := seconds -->
     
<!-- ATTRIBUTE postflighttime:
     Each station has to provide the Time needed by the passenger
     after leaving the aircraft to leave the vertiport in seconds.
     status := unimplemented
     format := seconds  -->
     
<!-- ATTRIBUTE defaultwaittime:
     An initial average waiting time for passengers at UAM stations can be defined. 
     This default waiting time is being included in UAM trip duration estimations 
     when no recorded waiting times are available from previous iterations
     (e.g. in the first iteration)
     status := unimplemented
     format := seconds  -->   
     
<!-- ATTRIBUTE link:
     Each node has to have a connecting link to the network.
     format := string -->
<!-- ============================================================ -->
    
<!-- ELEMENT vehicleType:
     A type of Urban Air Mobility vehicle. -->

<!-- ATTRIBUTE id:
     Each vehicle type has to have a unique id.
     format := string -->
          
<!-- ATTRIBUTE capacity:
     Each vehicle type has to have a passenger capacity.
     status := unimplemented
     format := unsigned integer -->
     
<!-- ATTRIBUTE range:
     Each vehicle type has to have a vehicle range.
     status := unimplemented
     format := double
     units  := meter -->
     
<!-- ATTRIBUTE cruisespeed:
     Each vehicle type has to have a cruise speed during level flight.
     status := unimplemented
     format := double
     units  := meter/second -->
     
<!-- ATTRIBUTE verticalspeed:
     Each vehicle type has to have a vertical speed during take-off and landing.
     status := unimplemented
     format := double
     units  := meter/second -->
     
<!-- ATTRIBUTE boardingtime:
     Each vehicle type has to provide the Time for the passenger to
     board in the aircraft in seconds.
     status := unimplemented
     format := seconds  -->                
     
<!-- ATTRIBUTE deboardingtime:
     Each vehicle type has to provide the Time for the passenger to
     board off from the aircraft in seconds.
     status := unimplemented
     format := seconds  -->                
     
<!-- ATTRIBUTE turnaroundtime:
     Each vehicle type has to provide the Time needed for the 
     UAM Vehicle to stay unavailable for other trips after
     landing in seconds.
     status := unimplemented
     format := seconds  -->   
     
<!-- ============================================================ -->
    
<!-- ELEMENT vehicle:
     An Urban Air Mobility vehicle. -->

<!-- ATTRIBUTE id:
     Each vehicle has to have a unique id.
     format := string -->
     
<!-- ATTRIBUTE type:
     Each vehicle has to have a type.
     format := string -->
     
<!-- ATTRIBUTE starttime:
     Each vehicle has to have the time of day of first possible vehicle usage.
     status := unimplemented
     format := "hh:mm:ss" -->
     
<!-- ATTRIBUTE endtime:
     Each vehicle has to have the time of day of latest vehicle usage ending.
     status := unimplemented
     format := "hh:mm:ss" -->
     
<!-- ATTRIBUTE initialstation:
     Each vehicle has to have the id of its base station at which at which it
     available at the start of the simulation/an iteration.
     format := string -->

=== BauhausLuftfahrt/MATSim-UAM/examples/uam-test-scenario/uam.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE uam SYSTEM "src/main/resources/dtd/uam.dtd">

<uam>
	<stations>
		<station id="00" name="station_00" preflighttime="60" postflighttime="600" defaultwaittime="0" link="uam_sl-uam_st_00_ga-uam_st_00_fa"/>
		<station id="01" name="station_01" preflighttime="600" postflighttime="60" defaultwaittime="0" link="uam_sl-uam_st_01_ga-uam_st_01_fa"/>
		<station id="04" name="station_04" preflighttime="600" postflighttime="60" defaultwaittime="0" link="uam_sl-uam_st_04_ga-uam_st_04_fa"/>
		<station id="05" name="station_05" preflighttime="60" postflighttime="600" defaultwaittime="0" link="uam_sl-uam_st_05_ga-uam_st_05_fa"/>
	</stations>
	<vehicleTypes>
		<vehicleType id="VEHTYPE1" capacity="1" range="100000" cruisespeed="33.33333" verticalspeed="10" boardingtime="30" deboardingtime="30" turnaroundtime="300"/>
		<vehicleType id="VEHTYPE2" capacity="2" range="10000" cruisespeed="22.22222" verticalspeed="10" boardingtime="30" deboardingtime="30" turnaroundtime="300"/>
	</vehicleTypes>
	<vehicles>
		<vehicle id="t1-1" type="VEHTYPE1" initialstation="00" starttime="00:00:00" endtime="30:00:00"/>
		<vehicle id="t1-2" type="VEHTYPE1" initialstation="01" starttime="00:00:00" endtime="30:00:00"/>
		<vehicle id="t2-1" type="VEHTYPE2" initialstation="04" starttime="00:00:00" endtime="30:00:00"/>
		<vehicle id="t2-2" type="VEHTYPE2" initialstation="05" starttime="00:00:00" endtime="30:00:00"/>
	</vehicles>
</uam>
